import { db } from '@/lib/db'

export const universitySeedData: any[] = [
  // ============================================================
  // IRAQ (10 universities)
  // ============================================================
  {
    name: "University of Baghdad",
    nameAr: "جامعة بغداد",
    country: "Iraq",
    city: "Baghdad",
    region: "Iraq",
    latitude: 33.3128,
    longitude: 44.3615,
    ranking: 801,
    rankingLocal: 1,
    minGpa: 2.6,
    minIelts: 5.0,
    minToefl: 61,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 2000,
    costOfLiving: 3600,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Law", "Business", "Science", "Arts", "Political Science", "Pharmacy", "Dentistry", "Computer Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.45,
    internationalStudents: 1200,
    totalStudents: 65000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://uobaghdad.edu.iq",
    description: "The University of Baghdad is Iraq's largest and oldest university, founded in 1957. It offers a comprehensive range of programs across sciences, engineering, humanities, and medicine. As the top-ranked institution in Iraq, it serves as the country's primary center for higher education and research.",
    tags: JSON.stringify(["top-iraq", "research", "comprehensive", "public", "affordable"]),
  },
  {
    name: "University of Mosul",
    nameAr: "جامعة الموصل",
    country: "Iraq",
    city: "Mosul",
    region: "Iraq",
    latitude: 36.3566,
    longitude: 43.1544,
    ranking: null,
    rankingLocal: 3,
    minGpa: 2.2,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1500,
    costOfLiving: 2400,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Law", "Science", "Arts", "Agriculture", "Computer Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.50,
    internationalStudents: 200,
    totalStudents: 40000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uomosul.edu.iq",
    description: "The University of Mosul is one of Iraq's largest educational institutions, established in 1967. It has been a historic center of learning in northern Iraq with strong programs in engineering and medicine. The university has shown remarkable resilience and continues to rebuild and expand its academic offerings.",
    tags: JSON.stringify(["iraq", "public", "affordable", "northern-iraq", "resilience"]),
  },
  {
    name: "University of Basrah",
    nameAr: "جامعة البصرة",
    country: "Iraq",
    city: "Basrah",
    region: "Iraq",
    latitude: 30.5085,
    longitude: 47.7964,
    ranking: null,
    rankingLocal: 4,
    minGpa: 2.2,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1500,
    costOfLiving: 2400,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Science", "Law", "Arts", "Marine Science", "Agriculture"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.48,
    internationalStudents: 150,
    totalStudents: 35000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uobasrah.edu.iq",
    description: "The University of Basrah is a major Iraqi university located in the southern port city of Basrah. It is particularly known for its marine science and engineering programs. Established in 1964, it serves as the primary higher education institution for southern Iraq.",
    tags: JSON.stringify(["iraq", "public", "affordable", "southern-iraq", "marine-science"]),
  },
  {
    name: "University of Technology, Baghdad",
    nameAr: "الجامعة التكنولوجية",
    country: "Iraq",
    city: "Baghdad",
    region: "Iraq",
    latitude: 33.3158,
    longitude: 44.4225,
    ranking: null,
    rankingLocal: 2,
    minGpa: 2.8,
    minIelts: 5.0,
    minToefl: 61,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Physics", "Chemistry", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 2000,
    costOfLiving: 3600,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Architecture", "Applied Sciences", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.35,
    internationalStudents: 300,
    totalStudents: 20000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uotechnology.edu.iq",
    description: "The University of Technology, Baghdad is Iraq's premier engineering and technology institution. Founded in 1975, it focuses exclusively on engineering, applied sciences, and architecture programs. It is widely regarded as the best technical university in Iraq with strong industry connections.",
    tags: JSON.stringify(["iraq", "public", "affordable", "engineering", "technology", "top-iraq"]),
  },
  {
    name: "University of Kufa",
    nameAr: "جامعة الكوفة",
    country: "Iraq",
    city: "Najaf",
    region: "Iraq",
    latitude: 32.0055,
    longitude: 44.3364,
    ranking: null,
    rankingLocal: 5,
    minGpa: 2.0,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1200,
    costOfLiving: 2400,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Engineering", "Law", "Science", "Arts", "Islamic Studies", "Business"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.52,
    internationalStudents: 100,
    totalStudents: 30000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uokufa.edu.iq",
    description: "The University of Kufa is located in the holy city of Najaf and is one of Iraq's rapidly growing universities. It offers diverse programs including medicine, engineering, and Islamic studies. The university has made significant investments in research infrastructure and international partnerships.",
    tags: JSON.stringify(["iraq", "public", "affordable", "najaf", "growing"]),
  },
  {
    name: "University of Babylon",
    nameAr: "جامعة بابل",
    country: "Iraq",
    city: "Babil",
    region: "Iraq",
    latitude: 32.4657,
    longitude: 44.4207,
    ranking: null,
    rankingLocal: 6,
    minGpa: 2.0,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1200,
    costOfLiving: 2000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Science", "Law", "Arts", "Management", "Computer Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.55,
    internationalStudents: 80,
    totalStudents: 28000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uobabylon.edu.iq",
    description: "The University of Babylon is located in Hilla, Babil Governorate, in the historic region of ancient Babylon. It has grown into a major academic center in central Iraq with strong programs in engineering and sciences. The university actively participates in international academic exchanges and research collaborations.",
    tags: JSON.stringify(["iraq", "public", "affordable", "central-iraq", "historical"]),
  },
  {
    name: "University of Kirkuk",
    nameAr: "جامعة كركوك",
    country: "Iraq",
    city: "Kirkuk",
    region: "Iraq",
    latitude: 35.4689,
    longitude: 44.3833,
    ranking: null,
    rankingLocal: 8,
    minGpa: 2.0,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1200,
    costOfLiving: 2200,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Science", "Law", "Arts", "Education"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.55,
    internationalStudents: 50,
    totalStudents: 22000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uokirkuk.edu.iq",
    description: "The University of Kirkuk serves the diverse community of Kirkuk Governorate in northern Iraq. It provides a range of academic programs and has been expanding its research capabilities. The university plays an important role in the region's educational and cultural development.",
    tags: JSON.stringify(["iraq", "public", "affordable", "northern-iraq"]),
  },
  {
    name: "University of Duhok",
    nameAr: "زانکۆی دهۆک",
    country: "Iraq",
    city: "Duhok",
    region: "Iraq",
    latitude: 36.8673,
    longitude: 42.9865,
    ranking: null,
    rankingLocal: 7,
    minGpa: 2.0,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "Kurdish"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1500,
    costOfLiving: 2400,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Science", "Arts", "Law", "Business", "Agriculture"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.50,
    internationalStudents: 200,
    totalStudents: 20000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uod.ac",
    description: "The University of Duhok is a prominent institution in the Kurdistan Region of Iraq. It teaches primarily in Kurdish and English, with programs spanning engineering, medicine, and humanities. The university has developed strong international partnerships, particularly with European institutions.",
    tags: JSON.stringify(["iraq", "kurdistan", "public", "affordable", "kurdish-medium"]),
  },
  {
    name: "American University of Iraq, Sulaimani",
    nameAr: "الجامعة الأمريكية في السليمانية",
    country: "Iraq",
    city: "Sulaimani",
    region: "Iraq",
    latitude: 35.5560,
    longitude: 45.4347,
    ranking: null,
    rankingLocal: 9,
    minGpa: 2.5,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 8000,
    costOfLiving: 3600,
    currency: "USD",
    programs: JSON.stringify(["Business Administration", "Computer Science", "Engineering", "International Studies", "Law", "English Literature", "MBA"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master"]),
    acceptanceRate: 0.40,
    internationalStudents: 150,
    totalStudents: 2500,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.auis.edu.krd",
    description: "The American University of Iraq, Sulaimani is a private, not-for-profit institution offering American-style education in the Kurdistan Region. All instruction is in English, making it accessible to international students. It is known for its strong business, IT, and engineering programs and modern campus facilities.",
    tags: JSON.stringify(["iraq", "kurdistan", "private", "english-medium", "american-style", "modern"]),
  },
  {
    name: "University of Erbil",
    nameAr: "زانکۆی هەولێر",
    country: "Iraq",
    city: "Erbil",
    region: "Iraq",
    latitude: 36.1911,
    longitude: 44.0091,
    ranking: null,
    rankingLocal: 10,
    minGpa: 2.0,
    minIelts: null,
    minToefl: null,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "Kurdish"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1500,
    costOfLiving: 3000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Science", "Arts", "Law", "Business"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.52,
    internationalStudents: 100,
    totalStudents: 18000,
    visaDifficulty: 1,
    scholarshipAvailable: true,
    website: "https://www.uoberbil.net",
    description: "The University of Erbil (Salahaddin University-Erbil) is the oldest and largest university in the Kurdistan Region of Iraq. Founded in 1968, it offers comprehensive programs in Kurdish, Arabic, and English. It is a leading research institution in northern Iraq with growing international connections.",
    tags: JSON.stringify(["iraq", "kurdistan", "public", "affordable", "oldest-kurdistan"]),
  },

  // ============================================================
  // GULF / ARAB (10 universities)
  // ============================================================
  {
    name: "American University of Sharjah",
    nameAr: "الجامعة الأمريكية في الشارقة",
    country: "UAE",
    city: "Sharjah",
    region: "Gulf",
    latitude: 25.2854,
    longitude: 55.4964,
    ranking: 380,
    rankingLocal: 8,
    minGpa: 3.0,
    minIelts: 6.5,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 20000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Business Administration", "Architecture", "Design", "Computer Science", "Communication", "International Studies", "Sciences"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master"]),
    acceptanceRate: 0.35,
    internationalStudents: 5000,
    totalStudents: 6500,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.aus.edu",
    description: "The American University of Sharjah is a coeducational institution of higher education in the UAE, based on the American model of higher education. It is accredited by the Middle States Commission on Higher Education. AUS is consistently ranked among the top universities in the region with a diverse student body from over 90 countries.",
    tags: JSON.stringify(["gulf", "uae", "private", "american-style", "accredited", "diverse"]),
  },
  {
    name: "American University of Beirut",
    nameAr: "الجامعة الأمريكية في بيروت",
    country: "Lebanon",
    city: "Beirut",
    region: "Gulf",
    latitude: 33.9007,
    longitude: 35.5045,
    ranking: 250,
    rankingLocal: 1,
    minGpa: 3.2,
    minIelts: 7.0,
    minToefl: 90,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 18000,
    costOfLiving: 8000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Business Administration", "Law", "Arts", "Sciences", "Agriculture", "Health Sciences", "Nursing"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MD"]),
    acceptanceRate: 0.20,
    internationalStudents: 3500,
    totalStudents: 9000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.aub.edu.lb",
    description: "The American University of Beirut is one of the most prestigious universities in the Middle East, founded in 1866. It follows the American liberal arts model and is consistently ranked as the top university in Lebanon and the Arab world. AUB has produced numerous leaders in government, business, and academia across the region.",
    tags: JSON.stringify(["gulf", "lebanon", "prestigious", "american-style", "research", "historic", "top-arab"]),
  },
  {
    name: "Qatar University",
    nameAr: "جامعة قطر",
    country: "Qatar",
    city: "Doha",
    region: "Gulf",
    latitude: 25.3797,
    longitude: 51.5254,
    ranking: 245,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 8000,
    costOfLiving: 10000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Business", "Law", "Education", "Arts", "Science", "Pharmacy", "Computer Science", "International Affairs"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.30,
    internationalStudents: 4000,
    totalStudents: 20000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.qu.edu.qa",
    description: "Qatar University is the national university of Qatar and the country's oldest and largest institution of higher education. It offers a wide range of programs with strong emphasis on research aligned with Qatar National Vision 2030. The university provides generous scholarships to international students and has state-of-the-art facilities.",
    tags: JSON.stringify(["gulf", "qatar", "public", "national", "scholarships", "research", "modern"]),
  },
  {
    name: "Khalifa University",
    nameAr: "جامعة خليفة",
    country: "UAE",
    city: "Abu Dhabi",
    region: "Gulf",
    latitude: 24.4169,
    longitude: 54.4764,
    ranking: 230,
    rankingLocal: 3,
    minGpa: 3.3,
    minIelts: 6.5,
    minToefl: 91,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Physics", "Chemistry", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Robotics", "Aerospace Engineering", "Biomedical Engineering", "Nuclear Engineering", "Petroleum Engineering", "Applied Mathematics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 3000,
    totalStudents: 5000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.ku.ac.ae",
    description: "Khalifa University is a world-class research university in Abu Dhabi, specializing in engineering, science, and technology. It is ranked among the top young universities globally and offers generous full scholarships including housing and stipends. The university is closely aligned with UAE's innovation and technology strategy.",
    tags: JSON.stringify(["gulf", "uae", "public", "research", "engineering", "scholarships", "technology", "stem"]),
  },
  {
    name: "University of Dubai",
    nameAr: "جامعة دبي",
    country: "UAE",
    city: "Dubai",
    region: "Gulf",
    latitude: 25.2520,
    longitude: 55.2828,
    ranking: null,
    rankingLocal: null,
    minGpa: 2.5,
    minIelts: 5.5,
    minToefl: 70,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 14000,
    costOfLiving: 15000,
    currency: "USD",
    programs: JSON.stringify(["Business Administration", "Engineering", "Computer Science", "Law", "Information Systems", "Finance"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "MBA"]),
    acceptanceRate: 0.45,
    internationalStudents: 2500,
    totalStudents: 3500,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.ud.ac.ae",
    description: "The University of Dubai is a private institution located in the heart of Dubai's academic city. It offers professionally oriented programs with strong industry connections in one of the world's most dynamic business hubs. The university focuses on practical, career-ready education with accreditation from the UAE Ministry of Education.",
    tags: JSON.stringify(["gulf", "uae", "private", "business", "career-focused"]),
  },
  {
    name: "King Saud University",
    nameAr: "جامعة الملك سعود",
    country: "Saudi Arabia",
    city: "Riyadh",
    region: "Gulf",
    latitude: 24.7136,
    longitude: 46.6753,
    ranking: 285,
    rankingLocal: 1,
    minGpa: 3.0,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 0,
    costOfLiving: 8000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Computer Science", "Business", "Law", "Science", "Arts", "Pharmacy", "Dentistry", "Architecture"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.30,
    internationalStudents: 5000,
    totalStudents: 55000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.ksu.edu.sa",
    description: "King Saud University is the oldest and largest university in Saudi Arabia, established in 1957. It is the top-ranked university in the kingdom and offers fully funded scholarships to international students including tuition, housing, and stipends. KSU has world-class research facilities and is a major center for Arabic language and Islamic studies.",
    tags: JSON.stringify(["gulf", "saudi", "public", "scholarships", "free-tuition", "top-saudi", "research"]),
  },
  {
    name: "American University in Cairo",
    nameAr: "الجامعة الأمريكية بالقاهرة",
    country: "Egypt",
    city: "Cairo",
    region: "Gulf",
    latitude: 30.0189,
    longitude: 31.4997,
    ranking: 395,
    rankingLocal: 2,
    minGpa: 3.0,
    minIelts: 6.5,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 5000,
    currency: "USD",
    programs: JSON.stringify(["Business Administration", "Engineering", "Computer Science", "Political Science", "Journalism", "Film", "Economics", "Sociology", "Psychology", "Law"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 3000,
    totalStudents: 7000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.aucegypt.edu",
    description: "The American University in Cairo is a leading English-language liberal arts university in the Middle East, founded in 1919. It is accredited in both Egypt and the United States and offers an American-style education. AUC is known for its strong programs in business, engineering, and political science, with a vibrant campus life.",
    tags: JSON.stringify(["gulf", "egypt", "private", "american-style", "liberal-arts", "english-medium", "prestigious"]),
  },
  {
    name: "United Arab Emirates University",
    nameAr: "جامعة الإمارات العربية المتحدة",
    country: "UAE",
    city: "Al Ain",
    region: "Gulf",
    latitude: 24.1915,
    longitude: 55.7606,
    ranking: 315,
    rankingLocal: 4,
    minGpa: 2.8,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 10000,
    costOfLiving: 10000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Business", "Science", "Education", "Law", "Information Technology", "Agriculture"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.35,
    internationalStudents: 2500,
    totalStudents: 15000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.uaeu.ac.ae",
    description: "The United Arab Emirates University is the national university of the UAE, located in Al Ain. Founded in 1976 by the late Sheikh Zayed, it is a comprehensive research university with strong programs across all disciplines. UAEU offers various scholarship programs for international students and has a beautiful, spacious campus.",
    tags: JSON.stringify(["gulf", "uae", "public", "national", "research", "comprehensive"]),
  },
  {
    name: "Jordan University of Science and Technology",
    nameAr: "جامعة العلوم والتكنولوجيا الأردنية",
    country: "Jordan",
    city: "Irbid",
    region: "Gulf",
    latitude: 32.4985,
    longitude: 35.8655,
    ranking: 400,
    rankingLocal: 2,
    minGpa: 2.8,
    minIelts: 5.5,
    minToefl: 70,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 6000,
    costOfLiving: 5000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Pharmacy", "Dentistry", "Computer Science", "Science", "Agriculture", "Veterinary Medicine", "Nursing"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.35,
    internationalStudents: 3000,
    totalStudents: 25000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.just.edu.jo",
    description: "Jordan University of Science and Technology is the leading technical university in Jordan, renowned for its engineering, medicine, and science programs. It is one of the most popular destinations for Iraqi students abroad due to its proximity and quality education. JUST has a modern campus with advanced research laboratories and hospital facilities.",
    tags: JSON.stringify(["gulf", "jordan", "public", "technology", "popular-iraqi", "medical", "affordable"]),
  },
  {
    name: "University of Jordan",
    nameAr: "الجامعة الأردنية",
    country: "Jordan",
    city: "Amman",
    region: "Gulf",
    latitude: 31.9525,
    longitude: 35.9340,
    ranking: 398,
    rankingLocal: 1,
    minGpa: 2.5,
    minIelts: 5.5,
    minToefl: 70,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "Arabic", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 5000,
    costOfLiving: 6000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Law", "Business", "Arts", "Science", "Pharmacy", "IT", "Political Science", "Economics", "Languages"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.40,
    internationalStudents: 4000,
    totalStudents: 40000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.ju.edu.jo",
    description: "The University of Jordan is the oldest and largest university in Jordan, established in 1962 in Amman. It is a comprehensive institution known for its strong academic reputation across the Arab world. The university is particularly popular among Iraqi students and offers a wide range of programs with affordable tuition.",
    tags: JSON.stringify(["gulf", "jordan", "public", "comprehensive", "popular-iraqi", "affordable", "historic"]),
  },

  // ============================================================
  // EUROPE (12 universities)
  // ============================================================
  {
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    region: "Europe",
    latitude: 48.2649,
    longitude: 11.6720,
    ranking: 50,
    rankingLocal: 1,
    minGpa: 2.5,
    minIelts: 6.5,
    minToefl: 88,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Physics", "Chemistry", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Natural Sciences", "Medicine", "Architecture", "Life Sciences", "Management", "Mathematics", "Physics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.10,
    internationalStudents: 16000,
    totalStudents: 50000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.tum.de",
    description: "The Technical University of Munich is one of Europe's top technical universities, consistently ranked as Germany's best university. It offers tuition-free education for all students regardless of nationality. TUM is renowned for its engineering, computer science, and natural sciences programs, with strong industry partnerships with BMW, Siemens, and others.",
    tags: JSON.stringify(["europe", "germany", "public", "tuition-free", "top-tier", "engineering", "research", "stem"]),
  },
  {
    name: "Ludwig Maximilian University of Munich",
    country: "Germany",
    city: "Munich",
    region: "Europe",
    latitude: 48.1497,
    longitude: 11.5780,
    ranking: 60,
    rankingLocal: 2,
    minGpa: 2.5,
    minIelts: 6.5,
    minToefl: 88,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Law", "Business", "Physics", "Biology", "Chemistry", "Psychology", "Philosophy", "History", "Computer Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "Medicine"]),
    acceptanceRate: 0.12,
    internationalStudents: 12000,
    totalStudents: 52000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.uni-muenchen.de",
    description: "Ludwig Maximilian University of Munich is one of Europe's oldest and most prestigious universities, founded in 1472. It is Germany's second-highest ranked university and also offers tuition-free education. LMU is particularly renowned for its medicine, life sciences, and humanities programs, having produced numerous Nobel laureates.",
    tags: JSON.stringify(["europe", "germany", "public", "tuition-free", "prestigious", "research", "historic", "humanities"]),
  },
  {
    name: "University of Vienna",
    country: "Austria",
    city: "Vienna",
    region: "Europe",
    latitude: 48.2128,
    longitude: 16.3635,
    ranking: 128,
    rankingLocal: 1,
    minGpa: 2.3,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 1500,
    costOfLiving: 10000,
    currency: "USD",
    programs: JSON.stringify(["Law", "Business", "Computer Science", "Psychology", "Philosophy", "Physics", "Chemistry", "Biology", "History", "Languages", "Political Science", "Medicine"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 12000,
    totalStudents: 90000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.univie.ac.at",
    description: "The University of Vienna is the largest university in the German-speaking world and one of the oldest in Europe, founded in 1365. It offers affordable education with low tuition fees even for non-EU students. The university is highly regarded for humanities, law, and sciences in one of the world's most livable cities.",
    tags: JSON.stringify(["europe", "austria", "public", "affordable", "historic", "largest", "livable-city"]),
  },
  {
    name: "Charles University",
    country: "Czech Republic",
    city: "Prague",
    region: "Europe",
    latitude: 50.0780,
    longitude: 14.4189,
    ranking: 236,
    rankingLocal: 1,
    minGpa: 2.3,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 5000,
    costOfLiving: 9000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Law", "Computer Science", "Pharmacy", "Science", "Social Sciences", "Economics", "Arts", "Mathematics", "Physics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "Medicine"]),
    acceptanceRate: 0.30,
    internationalStudents: 8000,
    totalStudents: 50000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.cuni.cz",
    description: "Charles University is the oldest university in Central Europe, founded in 1348 by Emperor Charles IV. It offers English-taught programs especially in medicine and sciences at competitive tuition rates. Located in beautiful Prague, it combines rich history with modern research facilities and a vibrant international community.",
    tags: JSON.stringify(["europe", "czech", "public", "historic", "english-programs", "medicine", "prague"]),
  },
  {
    name: "University of Warsaw",
    country: "Poland",
    city: "Warsaw",
    region: "Europe",
    latitude: 52.2192,
    longitude: 20.9846,
    ranking: 310,
    rankingLocal: 1,
    minGpa: 2.0,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 3000,
    costOfLiving: 7000,
    currency: "USD",
    programs: JSON.stringify(["Law", "Business", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology", "Economics", "Political Science", "Psychology"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.35,
    internationalStudents: 6000,
    totalStudents: 45000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://en.uw.edu.pl",
    description: "The University of Warsaw is the largest and highest-ranked university in Poland, founded in 1816. It offers affordable English-taught programs with a strong emphasis on research and international cooperation. The university is particularly known for its mathematics, physics, and economics departments in the dynamic city of Warsaw.",
    tags: JSON.stringify(["europe", "poland", "public", "affordable", "research", "mathematics", "english-programs"]),
  },
  {
    name: "University of Bologna",
    country: "Italy",
    city: "Bologna",
    region: "Europe",
    latitude: 44.4949,
    longitude: 11.3426,
    ranking: 133,
    rankingLocal: 1,
    minGpa: 2.3,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 2000,
    costOfLiving: 9000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Law", "Medicine", "Business", "Architecture", "Agriculture", "Science", "Arts", "Political Science", "Economics", "Design"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.30,
    internationalStudents: 10000,
    totalStudents: 87000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.unibo.it",
    description: "The University of Bologna is the oldest university in the Western world, founded in 1088, and is Italy's highest-ranked institution. It offers a unique educational experience in a beautiful Italian city with relatively low tuition fees. The university has strong programs across all disciplines and a very large international student community.",
    tags: JSON.stringify(["europe", "italy", "public", "affordable", "historic", "oldest-university", "culture"]),
  },
  {
    name: "Sorbonne University",
    country: "France",
    city: "Paris",
    region: "Europe",
    latitude: 48.8462,
    longitude: 2.3444,
    ranking: 60,
    rankingLocal: 1,
    minGpa: 2.5,
    minIelts: 6.5,
    minToefl: 88,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 15000,
    currency: "USD",
    programs: JSON.stringify(["Mathematics", "Physics", "Chemistry", "Computer Science", "Medicine", "Literature", "Languages", "History", "Philosophy", "Earth Sciences"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.15,
    internationalStudents: 10000,
    totalStudents: 55000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.sorbonne-universite.fr",
    description: "Sorbonne University is a world-class research university in the heart of Paris, formed from the historic Sorbonne. It offers very low tuition fees for all students regardless of nationality. The university excels in sciences, humanities, and medicine, with strong traditions in mathematics and literature.",
    tags: JSON.stringify(["europe", "france", "public", "affordable", "paris", "prestigious", "research", "historic"]),
  },
  {
    name: "University of Amsterdam",
    country: "Netherlands",
    city: "Amsterdam",
    region: "Europe",
    latitude: 52.3676,
    longitude: 4.9041,
    ranking: 53,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 92,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 14000,
    currency: "USD",
    programs: JSON.stringify(["Business", "Law", "Computer Science", "Medicine", "Psychology", "Economics", "Political Science", "Communication", "Humanities", "Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.15,
    internationalStudents: 10000,
    totalStudents: 39000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.uva.nl",
    description: "The University of Amsterdam is the largest university in the Netherlands and consistently ranked among Europe's top institutions. It offers a wide range of English-taught programs in a cosmopolitan and welcoming city. UvA is known for its strong research output and progressive teaching methods in all disciplines.",
    tags: JSON.stringify(["europe", "netherlands", "public", "english-taught", "research", "cosmopolitan", "progressive"]),
  },
  {
    name: "KU Leuven",
    country: "Belgium",
    city: "Leuven",
    region: "Europe",
    latitude: 50.8790,
    longitude: 4.7005,
    ranking: 70,
    rankingLocal: 1,
    minGpa: 2.5,
    minIelts: 6.5,
    minToefl: 88,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 5000,
    costOfLiving: 11000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Law", "Business", "Science", "Theology", "Arts", "Architecture", "Bioscience"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 10000,
    totalStudents: 60000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.kuleuven.be",
    description: "KU Leuven is Belgium's highest-ranked university and one of Europe's premier research institutions. Founded in 1425, it combines centuries of academic tradition with cutting-edge innovation. The university offers affordable tuition compared to other top European universities and has the largest independent research portfolio in Belgium.",
    tags: JSON.stringify(["europe", "belgium", "public", "affordable", "research", "historic", "innovation", "comprehensive"]),
  },
  {
    name: "Lund University",
    country: "Sweden",
    city: "Lund",
    region: "Europe",
    latitude: 55.7047,
    longitude: 13.1910,
    ranking: 85,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 90,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 10000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Business", "Law", "Science", "Architecture", "Design", "Social Sciences", "Economics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 5000,
    totalStudents: 40000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.lunduniversity.lu.se",
    description: "Lund University is one of Scandinavia's most prestigious universities, founded in 1666. It is one of Europe's top comprehensive research universities with world-class facilities. Lund is known for its innovation ecosystem, proximity to Copenhagen, and strong programs in engineering, medicine, and sustainability.",
    tags: JSON.stringify(["europe", "sweden", "public", "research", "innovation", "scandinavian", "sustainability"]),
  },
  {
    name: "University of Copenhagen",
    country: "Denmark",
    city: "Copenhagen",
    region: "Europe",
    latitude: 55.6761,
    longitude: 12.5683,
    ranking: 79,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 88,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Science", "Law", "Social Sciences", "Economics", "Computer Science", "Biology", "Chemistry", "Physics", "Pharmacy"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 5000,
    totalStudents: 38000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.ku.dk",
    description: "The University of Copenhagen is Denmark's highest-ranked university and a leading research institution in Northern Europe. Founded in 1479, it has produced numerous Nobel laureates. Located in one of the world's happiest cities, it offers outstanding programs in health sciences, natural sciences, and social sciences.",
    tags: JSON.stringify(["europe", "denmark", "public", "research", "nobel", "health-sciences", "scandinavian"]),
  },
  {
    name: "University of Helsinki",
    country: "Finland",
    city: "Helsinki",
    region: "Europe",
    latitude: 60.1699,
    longitude: 24.9384,
    ranking: 115,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 92,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 15000,
    costOfLiving: 9000,
    currency: "USD",
    programs: JSON.stringify(["Computer Science", "Medicine", "Law", "Science", "Agriculture", "Forestry", "Social Sciences", "Education", "Veterinary Medicine", "Pharmacy"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 3000,
    totalStudents: 31000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.helsinki.fi",
    description: "The University of Helsinki is Finland's largest and highest-ranked university, founded in 1640. It is a world leader in research and offers generous scholarships for international students. Located in the safe and beautiful Finnish capital, it is particularly strong in computer science, natural sciences, and education.",
    tags: JSON.stringify(["europe", "finland", "public", "research", "safe", "scholarships", "education", "technology"]),
  },

  // ============================================================
  // UK (6 universities)
  // ============================================================
  {
    name: "University of Oxford",
    country: "United Kingdom",
    city: "Oxford",
    region: "UK",
    latitude: 51.7520,
    longitude: -1.2577,
    ranking: 1,
    rankingLocal: 1,
    minGpa: 3.7,
    minIelts: 7.5,
    minToefl: 110,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 30000,
    costOfLiving: 15000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Law", "Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology", "History", "Philosophy", "Economics", "English Literature", "Political Science", "PPE"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.15,
    internationalStudents: 12000,
    totalStudents: 26000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.ox.ac.uk",
    description: "The University of Oxford is the oldest university in the English-speaking world, dating back to 1096, and is consistently ranked as the world's best university. It operates on the unique collegiate system and has produced 72 Nobel Prize laureates, 28 British prime ministers, and countless world leaders across all fields.",
    tags: JSON.stringify(["uk", "prestigious", "elite", "historic", "world-class", "competitive", "scholarships", "collegiate"]),
  },
  {
    name: "University of Cambridge",
    country: "United Kingdom",
    city: "Cambridge",
    region: "UK",
    latitude: 52.2053,
    longitude: 0.1218,
    ranking: 2,
    rankingLocal: 2,
    minGpa: 3.7,
    minIelts: 7.5,
    minToefl: 110,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 30000,
    costOfLiving: 14000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Mathematics", "Natural Sciences", "Law", "Economics", "History", "Philosophy", "English Literature", "Architecture"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.18,
    internationalStudents: 11000,
    totalStudents: 24000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.cam.ac.uk",
    description: "The University of Cambridge is one of the world's most prestigious universities, founded in 1209. Known for academic excellence in sciences and mathematics, it has produced 121 Nobel laureates, the most of any institution. Cambridge uses a collegiate system with intensive small-group teaching known as supervisions.",
    tags: JSON.stringify(["uk", "prestigious", "elite", "historic", "world-class", "sciences", "competitive", "collegiate"]),
  },
  {
    name: "Imperial College London",
    country: "United Kingdom",
    city: "London",
    region: "UK",
    latitude: 51.4988,
    longitude: -0.1749,
    ranking: 6,
    rankingLocal: 3,
    minGpa: 3.5,
    minIelts: 6.5,
    minToefl: 92,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Physics", "Chemistry", "English"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 35000,
    costOfLiving: 18000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Natural Sciences", "Mathematics", "Business", "Bioengineering", "Chemical Engineering", "Electrical Engineering"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MD"]),
    acceptanceRate: 0.15,
    internationalStudents: 15000,
    totalStudents: 22000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.imperial.ac.uk",
    description: "Imperial College London is a world-leading STEM university located in the heart of London. It is consistently ranked among the top 10 universities globally with a singular focus on science, engineering, medicine, and business. Imperial has one of the highest proportions of international students of any UK university and strong industry connections.",
    tags: JSON.stringify(["uk", "prestigious", "stem", "london", "research", "world-class", "innovation"]),
  },
  {
    name: "University College London",
    country: "United Kingdom",
    city: "London",
    region: "UK",
    latitude: 51.5246,
    longitude: -0.1340,
    ranking: 9,
    rankingLocal: 4,
    minGpa: 3.3,
    minIelts: 6.5,
    minToefl: 92,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 28000,
    costOfLiving: 18000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Law", "Business", "Computer Science", "Architecture", "Psychology", "Economics", "Political Science", "Neuroscience", "Education"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 18000,
    totalStudents: 46000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.ucl.ac.uk",
    description: "University College London is London's leading multidisciplinary university, founded in 1826 as the first university in England to admit students regardless of religion. It is known for its progressive ethos and outstanding research across all disciplines. UCL has a highly diverse international community and is located in the vibrant Bloomsbury district.",
    tags: JSON.stringify(["uk", "prestigious", "london", "comprehensive", "research", "diverse", "progressive"]),
  },
  {
    name: "University of Edinburgh",
    country: "United Kingdom",
    city: "Edinburgh",
    region: "UK",
    latitude: 55.9442,
    longitude: -3.1887,
    ranking: 22,
    rankingLocal: 5,
    minGpa: 3.2,
    minIelts: 6.5,
    minToefl: 92,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 25000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Law", "Engineering", "Computer Science", "Business", "Science", "Arts", "Informatics", "Veterinary Medicine", "Architecture", "Linguistics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 15000,
    totalStudents: 35000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.ed.ac.uk",
    description: "The University of Edinburgh is Scotland's highest-ranked university and one of the world's most prestigious institutions. Founded in 1583, it combines centuries of tradition with modern research excellence. Located in one of Europe's most beautiful cities, it is particularly strong in medicine, informatics, and humanities.",
    tags: JSON.stringify(["uk", "scotland", "prestigious", "historic", "research", "beautiful-city", "comprehensive"]),
  },
  {
    name: "University of Manchester",
    country: "United Kingdom",
    city: "Manchester",
    region: "UK",
    latitude: 53.4668,
    longitude: -2.2331,
    ranking: 32,
    rankingLocal: 6,
    minGpa: 3.0,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 22000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Business", "Law", "Science", "Arts", "Social Sciences", "Architecture", "Chemistry", "Physics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.30,
    internationalStudents: 18000,
    totalStudents: 44000,
    visaDifficulty: 4,
    scholarshipAvailable: true,
    website: "https://www.manchester.ac.uk",
    description: "The University of Manchester is the UK's largest single-site university and a member of the prestigious Russell Group. It has produced 25 Nobel laureates and is renowned for its research contributions, including the discovery of graphene. The university offers excellent programs across all disciplines in the vibrant city of Manchester.",
    tags: JSON.stringify(["uk", "prestigious", "russell-group", "research", "large", "graphene", "comprehensive"]),
  },

  // ============================================================
  // US / CANADA (6 universities)
  // ============================================================
  {
    name: "Massachusetts Institute of Technology",
    country: "United States",
    city: "Cambridge, MA",
    region: "North America",
    latitude: 42.3601,
    longitude: -71.0942,
    ranking: 1,
    rankingLocal: 1,
    minGpa: 3.8,
    minIelts: 7.5,
    minToefl: 100,
    minSat: 1500,
    requiredSubjects: JSON.stringify(["Mathematics", "Physics", "Chemistry", "English"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 55000,
    costOfLiving: 20000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology", "Economics", "Architecture", "Brain Sciences", "Data Science", "AI"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.04,
    internationalStudents: 3500,
    totalStudents: 11500,
    visaDifficulty: 5,
    scholarshipAvailable: true,
    website: "https://www.mit.edu",
    description: "MIT is widely regarded as the world's best university for science, technology, and engineering. Founded in 1861, it has produced 98 Nobel laureates and is at the forefront of innovation in AI, biotechnology, and quantum computing. MIT's entrepreneurial culture has spawned thousands of companies worth trillions of dollars combined.",
    tags: JSON.stringify(["usa", "elite", "prestigious", "technology", "engineering", "research", "entrepreneurship", "innovation"]),
  },
  {
    name: "Stanford University",
    country: "United States",
    city: "Stanford, CA",
    region: "North America",
    latitude: 37.4275,
    longitude: -122.1697,
    ranking: 3,
    rankingLocal: 3,
    minGpa: 3.7,
    minIelts: 7.0,
    minToefl: 100,
    minSat: 1480,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 55000,
    costOfLiving: 22000,
    currency: "USD",
    programs: JSON.stringify(["Computer Science", "Engineering", "Business", "Medicine", "Law", "Mathematics", "Physics", "Biology", "Psychology", "Data Science", "AI", "Design"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MBA", "MD", "JD"]),
    acceptanceRate: 0.04,
    internationalStudents: 3500,
    totalStudents: 17500,
    visaDifficulty: 5,
    scholarshipAvailable: true,
    website: "https://www.stanford.edu",
    description: "Stanford University is one of the world's most prestigious universities, located in the heart of Silicon Valley. Founded in 1885, it has been instrumental in the development of the technology industry and counts Google, Yahoo, and HP among its alumni creations. Stanford offers unparalleled opportunities for innovation and entrepreneurship.",
    tags: JSON.stringify(["usa", "elite", "prestigious", "silicon-valley", "innovation", "entrepreneurship", "technology"]),
  },
  {
    name: "Harvard University",
    country: "United States",
    city: "Cambridge, MA",
    region: "North America",
    latitude: 42.3770,
    longitude: -71.1167,
    ranking: 4,
    rankingLocal: 2,
    minGpa: 3.7,
    minIelts: 7.0,
    minToefl: 100,
    minSat: 1480,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: false,
    tuitionPerYear: 52000,
    costOfLiving: 20000,
    currency: "USD",
    programs: JSON.stringify(["Law", "Medicine", "Business", "Computer Science", "Engineering", "Economics", "Political Science", "Psychology", "Biology", "Mathematics", "History", "Philosophy", "Government"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MBA", "MD", "JD"]),
    acceptanceRate: 0.03,
    internationalStudents: 4000,
    totalStudents: 23000,
    visaDifficulty: 5,
    scholarshipAvailable: true,
    website: "https://www.harvard.edu",
    description: "Harvard University is the oldest institution of higher education in the United States, founded in 1636, and arguably the world's most famous university. It has produced 8 US presidents, 161 Nobel laureates, and countless world leaders. Harvard's unparalleled resources, faculty, and alumni network make it the gold standard of higher education.",
    tags: JSON.stringify(["usa", "elite", "prestigious", "historic", "world-class", "ivy-league", "competitive", "leaders"]),
  },
  {
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    region: "North America",
    latitude: 43.6532,
    longitude: -79.3832,
    ranking: 21,
    rankingLocal: 1,
    minGpa: 3.0,
    minIelts: 6.5,
    minToefl: 89,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 40000,
    costOfLiving: 15000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Law", "Business", "Science", "Arts", "Architecture", "Nursing", "Pharmacy", "Dentistry", "Kinesiology"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MD", "JD"]),
    acceptanceRate: 0.15,
    internationalStudents: 20000,
    totalStudents: 95000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.utoronto.ca",
    description: "The University of Toronto is Canada's highest-ranked university and one of the world's top comprehensive research institutions. Founded in 1827, it is a global leader in research, particularly in AI, medicine, and engineering. U of T has three campuses in Toronto and is known for its incredible diversity with students from over 160 countries.",
    tags: JSON.stringify(["canada", "prestigious", "research", "diverse", "ai-research", "comprehensive", "world-class"]),
  },
  {
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver",
    region: "North America",
    latitude: 49.2606,
    longitude: -123.2460,
    ranking: 34,
    rankingLocal: 2,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 90,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 35000,
    costOfLiving: 12000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Medicine", "Business", "Science", "Arts", "Forestry", "Land and Food Systems", "Kinesiology"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 16000,
    totalStudents: 67000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.ubc.ca",
    description: "The University of British Columbia is one of Canada's top three universities, located in the stunning city of Vancouver. Founded in 1908, it is renowned for its beautiful campus overlooking the ocean and mountains. UBC excels in environmental sciences, forestry, and sustainability research, while also maintaining strong programs across all disciplines.",
    tags: JSON.stringify(["canada", "prestigious", "research", "beautiful-campus", "sustainability", "vancouver", "comprehensive"]),
  },
  {
    name: "McGill University",
    country: "Canada",
    city: "Montreal",
    region: "North America",
    latitude: 45.5048,
    longitude: -73.5772,
    ranking: 30,
    rankingLocal: 3,
    minGpa: 2.8,
    minIelts: 6.5,
    minToefl: 86,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 30000,
    costOfLiving: 10000,
    currency: "USD",
    programs: JSON.stringify(["Medicine", "Engineering", "Computer Science", "Law", "Business", "Science", "Arts", "Music", "Architecture", "Agriculture", "Nursing", "Dentistry"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD", "MD", "JD"]),
    acceptanceRate: 0.18,
    internationalStudents: 12000,
    totalStudents: 40000,
    visaDifficulty: 3,
    scholarshipAvailable: true,
    website: "https://www.mcgill.ca",
    description: "McGill University is Canada's most internationally diverse university, located in the vibrant bilingual city of Montreal. Founded in 1821, it has a reputation for academic excellence and research intensity. McGill offers lower tuition than many comparable institutions and is known for its strong medicine, engineering, and arts programs.",
    tags: JSON.stringify(["canada", "prestigious", "research", "diverse", "montreal", "bilingual", "affordable-prestige"]),
  },

  // ============================================================
  // TURKEY / MALAYSIA (6 universities)
  // ============================================================
  {
    name: "Boğaziçi University",
    country: "Turkey",
    city: "Istanbul",
    region: "Asia",
    latitude: 41.0862,
    longitude: 29.0533,
    ranking: 700,
    rankingLocal: 2,
    minGpa: 2.5,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 6000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Economics", "Business Administration", "Arts", "Sciences", "Education", "Psychology", "Sociology", "Political Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.15,
    internationalStudents: 2000,
    totalStudents: 17000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.boun.edu.tr",
    description: "Boğaziçi University is one of Turkey's most prestigious universities, located on the beautiful Bosphorus strait in Istanbul. Founded in 1863 as Robert College, it was the first American college outside the US. All instruction is in English, and it offers extremely affordable tuition with a stunning campus and strong academic reputation.",
    tags: JSON.stringify(["turkey", "prestigious", "english-medium", "affordable", "istanbul", "historic", "scenic"]),
  },
  {
    name: "Middle East Technical University",
    country: "Turkey",
    city: "Ankara",
    region: "Asia",
    latitude: 39.9208,
    longitude: 32.8541,
    ranking: 600,
    rankingLocal: 3,
    minGpa: 2.5,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 5000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Architecture", "Science", "Business", "Economics", "Education", "Arts", "Social Sciences"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.18,
    internationalStudents: 3000,
    totalStudents: 28000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.metu.edu.tr",
    description: "Middle East Technical University (METU) is one of Turkey's leading technical universities, located in Ankara. Founded in 1956, it teaches entirely in English and is renowned for its engineering and science programs. METU has a massive forested campus and is known for its strong research output and vibrant student life.",
    tags: JSON.stringify(["turkey", "engineering", "english-medium", "affordable", "research", "forested-campus"]),
  },
  {
    name: "Istanbul Technical University",
    country: "Turkey",
    city: "Istanbul",
    region: "Asia",
    latitude: 41.1054,
    longitude: 29.0220,
    ranking: 800,
    rankingLocal: 4,
    minGpa: 2.3,
    minIelts: 5.5,
    minToefl: 72,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 500,
    costOfLiving: 6000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Architecture", "Computer Science", "Science", "Naval Architecture", "Aerospace Engineering", "Textile Engineering", "Management"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.25,
    internationalStudents: 3000,
    totalStudents: 35000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.itu.edu.tr",
    description: "Istanbul Technical University is Turkey's oldest technical university, founded in 1773. It is one of the most prominent engineering institutions in the region with a long tradition of producing leading engineers and architects. ITU offers affordable English-taught programs in the dynamic city of Istanbul.",
    tags: JSON.stringify(["turkey", "engineering", "affordable", "istanbul", "historic", "architecture"]),
  },
  {
    name: "University of Malaya",
    country: "Malaysia",
    city: "Kuala Lumpur",
    region: "Asia",
    latitude: 3.1203,
    longitude: 101.6514,
    ranking: 60,
    rankingLocal: 1,
    minGpa: 2.8,
    minIelts: 6.0,
    minToefl: 80,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English", "Science"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 5000,
    costOfLiving: 6000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Medicine", "Computer Science", "Business", "Law", "Science", "Arts", "Education", "Dentistry", "Pharmacy", "Economics"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.20,
    internationalStudents: 5000,
    totalStudents: 30000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.um.edu.my",
    description: "The University of Malaya is Malaysia's oldest and highest-ranked university, established in 1905. Located in Kuala Lumpur, it is a research-intensive institution with strong programs across all disciplines. UM offers affordable tuition, a multicultural environment, and is a gateway to Asia's growing economic opportunities.",
    tags: JSON.stringify(["malaysia", "prestigious", "affordable", "research", "kuala-lumpur", "multicultural", "gateway-asia"]),
  },
  {
    name: "Universiti Teknologi Malaysia",
    country: "Malaysia",
    city: "Johor Bahru",
    region: "Asia",
    latitude: 1.5606,
    longitude: 103.6364,
    ranking: 200,
    rankingLocal: 2,
    minGpa: 2.5,
    minIelts: 5.5,
    minToefl: 72,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "Science", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 3000,
    costOfLiving: 4000,
    currency: "USD",
    programs: JSON.stringify(["Engineering", "Computer Science", "Architecture", "Science", "Management", "Urban Planning", "Biosciences", "Geoinformation"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.30,
    internationalStudents: 5000,
    totalStudents: 28000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.utm.my",
    description: "Universiti Teknologi Malaysia (UTM) is Malaysia's premier engineering and technology university, located in Johor Bahru near Singapore. Founded in 1904, it has strong industry connections and is known for its practical, career-focused education. UTM offers very affordable tuition and has a large international student community.",
    tags: JSON.stringify(["malaysia", "engineering", "affordable", "technology", "career-focused", "near-singapore"]),
  },
  {
    name: "Taylor's University",
    country: "Malaysia",
    city: "Subang Jaya",
    region: "Asia",
    latitude: 3.0755,
    longitude: 101.6116,
    ranking: 284,
    rankingLocal: 5,
    minGpa: 2.3,
    minIelts: 5.5,
    minToefl: 70,
    minSat: null,
    requiredSubjects: JSON.stringify(["Mathematics", "English"]),
    acceptsIraqiSystem: true,
    tuitionPerYear: 6000,
    costOfLiving: 5000,
    currency: "USD",
    programs: JSON.stringify(["Business", "Computer Science", "Engineering", "Medicine", "Law", "Hospitality", "Design", "Architecture", "Communication", "Education", "Food Science"]),
    degreesOffered: JSON.stringify(["Bachelor", "Master", "PhD"]),
    acceptanceRate: 0.40,
    internationalStudents: 5000,
    totalStudents: 10000,
    visaDifficulty: 2,
    scholarshipAvailable: true,
    website: "https://www.taylors.edu.my",
    description: "Taylor's University is one of Malaysia's top private universities, known for its modern facilities and industry-aligned programs. Located in Subang Jaya near Kuala Lumpur, it has a strong reputation for business, hospitality, and design programs. Taylor's offers a vibrant campus life with excellent student support services.",
    tags: JSON.stringify(["malaysia", "private", "modern", "industry-aligned", "hospitality", "design", "kuala-lumpur"]),
  },
]

export async function seedUniversities() {
  console.log(`🗑️  Clearing existing university data...`)
  await db.university.deleteMany()

  console.log(`🌱 Seeding ${universitySeedData.length} universities...`)
  const result = await db.university.createMany({
    data: universitySeedData,
    skipDuplicates: true,
  })

  console.log(`✅ Successfully seeded ${result.count} universities!`)
  console.log(
    `   📊 Breakdown by region:`
  )

  const regions = universitySeedData.reduce((acc, u) => {
    acc[u.region] = (acc[u.region] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  for (const [region, count] of Object.entries(regions)) {
    console.log(`      ${region}: ${count} universities`)
  }

  return result
}
